# Generated by Django 2.0 on 2018-01-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(default=None, max_length=32, null=True, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='权限名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='座机')),
                ('mobile', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='手机')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='admininfo',
            name='permission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Permission'),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='userpro',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile'),
        ),
    ]
