# Generated by Django 2.0 on 2018-01-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180119_1438'),
    ]

    operations = [
    ]
