# Generated by Django 2.0 on 2018-01-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180124_1035'),
    ]

    operations = [
    ]
