# Generated by Django 2.0 on 2018-01-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_wechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wechat',
            field=models.CharField(blank=True, default=None, max_length=64, verbose_name='微信号'),
        ),
    ]
