# Generated by Django 2.0 on 2018-01-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20180119_1438'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='设备名称')),
                ('code', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='序列号')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('worth', models.FloatField(blank=True, default=None, null=True, verbose_name='采购金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('guaranteed', models.IntegerField(blank=True, default=None, null=True, verbose_name='保修期限')),
                ('production_date', models.DateField(blank=True, default=None, null=True, verbose_name='生产日期')),
                ('up_date', models.DateField(blank=True, default=None, null=True, verbose_name='上架日期')),
            ],
        ),
        migrations.CreateModel(
            name='Business_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='所属业务')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='机房名称')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名称')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Business_unit', verbose_name='所属业务'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Room', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='userpro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='设备负责人'),
        ),
    ]
