# Generated by Django 2.0 on 2018-01-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180119_1618'),
    ]

    operations = [
    ]
