# Generated by Django 2.0 on 2018-01-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180124_1006'),
    ]

    operations = [
    ]
