# Generated by Django 2.0 on 2018-01-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20180119_1438'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_deal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_action', models.IntegerField(verbose_name='处理结果')),
                ('change_note', models.TextField(verbose_name='处理意见')),
            ],
        ),
        migrations.CreateModel(
            name='change_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_num', models.IntegerField(verbose_name='步骤编号')),
                ('flow_name', models.CharField(max_length=32, verbose_name='流程名称')),
                ('flow_repeat_no', models.IntegerField(verbose_name='审批次数')),
                ('flow_verify_people', models.BooleanField(verbose_name='指定审核人员')),
                ('flow_role', models.ManyToManyField(to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='change_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_device', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='关联设备')),
                ('change_theme', models.CharField(default=None, max_length=100, null=True, verbose_name='变更主题')),
                ('change_target', models.TextField(blank=True, default=None, null=True, verbose_name='变更目的')),
                ('change_plan', models.TextField(blank=True, default=None, null=True, verbose_name='变更方案')),
                ('change_back', models.TextField(blank=True, default=None, null=True, verbose_name='回退方案')),
                ('change_note', models.TextField(blank=True, default=None, null=True, verbose_name='变更记录')),
                ('change_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_create_people', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_create_people', to='account.UserProfile')),
                ('change_flow', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_flow')),
                ('change_partner', models.ManyToManyField(default=None, to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='change_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='变更类型')),
            ],
        ),
        migrations.CreateModel(
            name='next_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_flow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_flow', verbose_name='关联动作')),
                ('change_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_info', verbose_name='关联工作流')),
                ('next_people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联下一处理人')),
            ],
        ),
        migrations.AddField(
            model_name='change_info',
            name='change_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_type'),
        ),
        migrations.AddField(
            model_name='change_info',
            name='change_verify_people',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_verify_people', to='account.UserProfile'),
        ),
        migrations.AddField(
            model_name='change_deal_info',
            name='change_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_flow', verbose_name='关联步骤'),
        ),
        migrations.AddField(
            model_name='change_deal_info',
            name='change_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_info', verbose_name='关联变更'),
        ),
        migrations.AddField(
            model_name='change_deal_info',
            name='change_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联处理人'),
        ),
    ]
