# Generated by Django 2.0 on 2018-01-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_auto_20180119_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_deal_info',
            name='change_note',
            field=models.TextField(null=True, verbose_name='处理意见'),
        ),
        migrations.AlterField(
            model_name='next_people',
            name='change_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_info', verbose_name='关联'),
        ),
    ]
