# Generated by Django 2.0 on 2018-01-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_auto_20180119_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='next_people',
            name='change_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_info', verbose_name='关联变更'),
        ),
    ]
