# Generated by Django 2.0 on 2018-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180119_1438'),
        ('procedures', '0004_auto_20180119_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='next_people',
            name='next_people',
        ),
        migrations.AddField(
            model_name='next_people',
            name='next_people',
            field=models.ManyToManyField(to='account.UserProfile', verbose_name='关联下一处理人'),
        ),
    ]
