# Generated by Django 2.0 on 2018-01-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_auto_20180119_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='next_people',
            name='next_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联下一处理人'),
        ),
    ]
