# Generated by Django 2.0 on 2018-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180119_1438'),
        ('procedures', '0007_auto_20180119_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_deal_info',
            name='change_people',
        ),
        migrations.AddField(
            model_name='change_deal_info',
            name='change_people',
            field=models.ManyToManyField(to='account.UserProfile', verbose_name='关联处理人'),
        ),
    ]
