# Generated by Django 2.0 on 2018-01-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0009_remove_next_people_next_people'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='next_people',
            new_name='change_next_people',
        ),
    ]
