# Generated by Django 2.0 on 2018-01-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0013_change_deal_info_change_deal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_deal_info',
            name='change_deal_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='处理时间'),
        ),
    ]
