# Generated by Django 2.0 on 2018-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0014_auto_20180122_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_deal_info',
            name='change_action',
            field=models.IntegerField(null=True, verbose_name='处理结果'),
        ),
    ]
