# Generated by Django 2.0 on 2018-01-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180119_1618'),
        ('procedures', '0025_auto_20180124_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_next_people',
            name='next_people_id',
        ),
        migrations.AddField(
            model_name='change_next_people',
            name='next_people',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联处理人'),
        ),
    ]
