# Generated by Django 2.0 on 2018-01-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180119_1618'),
        ('procedures', '0027_remove_change_next_people_change_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_next_people',
            name='next_people',
        ),
        migrations.AddField(
            model_name='change_next_people',
            name='change_flow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_flow', verbose_name='关联动作'),
        ),
        migrations.AddField(
            model_name='change_next_people',
            name='next_persion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联处理人'),
        ),
    ]
