# Generated by Django 2.0 on 2018-01-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0029_remove_change_next_people_next_persion'),
    ]

    operations = [
    ]
