# Generated by Django 2.0 on 2018-01-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180124_1037'),
        ('procedures', '0032_auto_20180124_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_next_people',
            name='next_persion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联处理人'),
        ),
        migrations.AlterField(
            model_name='change_deal_info',
            name='change_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联处理人'),
        ),
        migrations.AlterField(
            model_name='change_info',
            name='change_device',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='change_next_people',
            name='change_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.change_flow', verbose_name='关联动作'),
        ),
        migrations.AlterField(
            model_name='change_type',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='变更类型'),
        ),
    ]
