# Generated by Django 2.0 on 2018-01-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0033_auto_20180124_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_next_people',
            old_name='next_persion',
            new_name='next_people',
        ),
    ]
