# Generated by Django 2.0 on 2018-01-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0037_auto_20180124_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_info',
            name='change_verify_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_verify_people', to='account.UserProfile'),
        ),
    ]
