# Generated by Django 2.0 on 2018-01-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180124_1037'),
        ('procedures', '0038_auto_20180124_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_deal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_deal_time', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('event_action', models.IntegerField(null=True, verbose_name='处理结果')),
                ('event_note', models.TextField(blank=True, null=True, verbose_name='处理意见')),
            ],
        ),
        migrations.CreateModel(
            name='event_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_num', models.IntegerField(verbose_name='步骤编号')),
                ('flow_name', models.CharField(max_length=32, verbose_name='流程名称')),
                ('flow_role', models.ManyToManyField(to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='关联资产')),
                ('event_theme', models.CharField(default=None, max_length=100, null=True, verbose_name='事件主题')),
                ('event_description', models.TextField(blank=True, default=None, null=True, verbose_name='事件描述')),
                ('event_start_time', models.DateTimeField(auto_now_add=True, verbose_name='产生时间')),
                ('event_create_people', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_create_people', to='account.UserProfile', verbose_name='创建人')),
                ('event_deal_people', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_deal_people', to='account.UserProfile', verbose_name='指派人员')),
            ],
        ),
        migrations.CreateModel(
            name='event_next_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_flow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.event_flow', verbose_name='关联动作')),
                ('event_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.event_info', verbose_name='关联事件')),
                ('next_people', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联处理人')),
            ],
        ),
        migrations.CreateModel(
            name='event_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='事件类型')),
            ],
        ),
        migrations.AddField(
            model_name='event_info',
            name='event_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.event_type', verbose_name='事件分类'),
        ),
        migrations.AddField(
            model_name='event_deal_info',
            name='event_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.event_flow', verbose_name='关联步骤'),
        ),
        migrations.AddField(
            model_name='event_deal_info',
            name='event_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.event_info', verbose_name='关联事件'),
        ),
        migrations.AddField(
            model_name='event_deal_info',
            name='event_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='关联处理人'),
        ),
    ]
