# Generated by Django 2.0 on 2018-01-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0039_auto_20180124_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='event_flow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='procedures.event_flow', verbose_name='关联流程'),
        ),
    ]
