# Generated by Django 2.0 on 2018-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0040_event_info_event_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='event_flag',
            field=models.IntegerField(default=None, verbose_name='事件状态'),
        ),
    ]
