# Generated by Django 2.0 on 2018-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0041_event_info_event_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_flow',
            name='flow_role',
            field=models.ManyToManyField(blank=True, to='account.UserProfile'),
        ),
    ]
