# Generated by Django 2.0 on 2018-01-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0042_auto_20180124_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_flow',
            name='flow_repeat_no',
            field=models.IntegerField(blank=True, verbose_name='审批次数'),
        ),
        migrations.AlterField(
            model_name='change_flow',
            name='flow_role',
            field=models.ManyToManyField(blank=True, to='account.UserProfile'),
        ),
    ]
