# Generated by Django 2.0 on 2018-02-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_start_day', models.DateField(verbose_name='开始日期')),
                ('business_end_day', models.DateField(verbose_name='结束日期')),
                ('business_start_time', models.TimeField(verbose_name='开始时间')),
                ('business_end_time', models.TimeField(verbose_name='结束时间')),
                ('business_name', models.CharField(max_length=32, verbose_name='业务名称')),
                ('business_remark', models.TextField(verbose_name='业务备注')),
            ],
        ),
    ]
